import 'package:flutter/material.dart';

class AppConstants {
  static const YOUTUBE_BASE_URL = "https://www.youtube.com/embed/";
  static const IMAGE_BASE_URL = "http://image.tmdb.org/t/p/";
  static const IMAGE_SECURE_BASE_URL = "https://image.tmdb.org/t/p/";
  static const BACKDROP_SIZES = ["w300", "w780", "w1280", "original"];
  static const POSTER_SIZES = [
    "w92",
    "w154",
    "w185",
    "w342",
    "w500",
    "w780",
    "original"
  ];

  static const DATA_LANGUAGES = [
    {"shotcut": "bi", "english_name": "Bislama", "name": ""},
    {"shotcut": "cs", "english_name": "Czech", "name": "Český"},
    {"shotcut": "ba", "english_name": "Bashkir", "name": ""},
    {"shotcut": "ae", "english_name": "Avestan", "name": ""},
    {"shotcut": "av", "english_name": "Avaric", "name": ""},
    {"shotcut": "de", "english_name": "German", "name": "Deutsch"},
    {"shotcut": "mt", "english_name": "Maltese", "name": "Malti"},
    {"shotcut": "om", "english_name": "Oromo", "name": ""},
    {"shotcut": "rm", "english_name": "Raeto-Romance", "name": ""},
    {"shotcut": "so", "english_name": "Somali", "name": "Somali"},
    {"shotcut": "ts", "english_name": "Tsonga", "name": ""},
    {"shotcut": "vi", "english_name": "Vietnamese", "name": "Tiếng Việt"},
    {"shotcut": "gn", "english_name": "Guarani", "name": ""},
    {"shotcut": "ig", "english_name": "Igbo", "name": ""},
    {"shotcut": "it", "english_name": "Italian", "name": "Italiano"},
    {"shotcut": "ki", "english_name": "Kikuyu", "name": ""},
    {"shotcut": "ku", "english_name": "Kurdish", "name": ""},
    {"shotcut": "la", "english_name": "Latin", "name": "Latin"},
    {"shotcut": "ln", "english_name": "Lingala", "name": ""},
    {"shotcut": "lb", "english_name": "Letzeburgesch", "name": ""},
    {"shotcut": "ny", "english_name": "Chichewa; Nyanja", "name": ""},
    {"shotcut": "pl", "english_name": "Polish", "name": "Polski"},
    {"shotcut": "si", "english_name": "Sinhalese", "name": "සිංහල"},
    {"shotcut": "to", "english_name": "Tonga", "name": ""},
    {"shotcut": "az", "english_name": "Azerbaijani", "name": "Azərbaycan"},
    {"shotcut": "ce", "english_name": "Chechen", "name": ""},
    {"shotcut": "cu", "english_name": "Slavic", "name": ""},
    {"shotcut": "da", "english_name": "Danish", "name": "Dansk"},
    {"shotcut": "hz", "english_name": "Herero", "name": ""},
    {"shotcut": "ie", "english_name": "Interlingue", "name": ""},
    {"shotcut": "rw", "english_name": "Kinyarwanda", "name": "Kinyarwanda"},
    {"shotcut": "mi", "english_name": "Maori", "name": ""},
    {"shotcut": "no", "english_name": "Norwegian", "name": "Norsk"},
    {"shotcut": "pi", "english_name": "Pali", "name": ""},
    {"shotcut": "sk", "english_name": "Slovak", "name": "Slovenčina"},
    {"shotcut": "se", "english_name": "Northern Sami", "name": ""},
    {"shotcut": "sm", "english_name": "Samoan", "name": ""},
    {"shotcut": "uk", "english_name": "Ukrainian", "name": "Український"},
    {"shotcut": "en", "english_name": "English", "name": "English"},
    {"shotcut": "ay", "english_name": "Aymara", "name": ""},
    {"shotcut": "ca", "english_name": "Catalan", "name": "Català"},
    {"shotcut": "eo", "english_name": "Esperanto", "name": "Esperanto"},
    {"shotcut": "ha", "english_name": "Hausa", "name": "Hausa"},
    {"shotcut": "ho", "english_name": "Hiri Motu", "name": ""},
    {"shotcut": "hu", "english_name": "Hungarian", "name": "Magyar"},
    {"shotcut": "io", "english_name": "Ido", "name": ""},
    {"shotcut": "ii", "english_name": "Yi", "name": ""},
    {"shotcut": "kn", "english_name": "Kannada", "name": "?????"},
    {"shotcut": "kv", "english_name": "Komi", "name": ""},
    {"shotcut": "li", "english_name": "Limburgish", "name": ""},
    {"shotcut": "oj", "english_name": "Ojibwa", "name": ""},
    {"shotcut": "ru", "english_name": "Russian", "name": "Pусский"},
    {"shotcut": "sr", "english_name": "Serbian", "name": "Srpski"},
    {"shotcut": "sv", "english_name": "Swedish", "name": "svenska"},
    {"shotcut": "ty", "english_name": "Tahitian", "name": ""},
    {"shotcut": "zu", "english_name": "Zulu", "name": "isiZulu"},
    {"shotcut": "ka", "english_name": "Georgian", "name": "ქართული"},
    {"shotcut": "ch", "english_name": "Chamorro", "name": "Finu' Chamorro"},
    {"shotcut": "be", "english_name": "Belarusian", "name": "беларуская мова"},
    {"shotcut": "br", "english_name": "Breton", "name": ""},
    {"shotcut": "kw", "english_name": "Cornish", "name": ""},
    {"shotcut": "fi", "english_name": "Finnish", "name": "suomi"},
    {"shotcut": "sh", "english_name": "Serbo-Croatian", "name": ""},
    {"shotcut": "nn", "english_name": "Norwegian Nynorsk", "name": ""},
    {"shotcut": "tt", "english_name": "Tatar", "name": ""},
    {"shotcut": "tg", "english_name": "Tajik", "name": ""},
    {"shotcut": "vo", "english_name": "Volapük", "name": ""},
    {"shotcut": "ps", "english_name": "Pushto", "name": "پښتو"},
    {"shotcut": "mk", "english_name": "Macedonian", "name": ""},
    {"shotcut": "fr", "english_name": "French", "name": "Français"},
    {"shotcut": "bm", "english_name": "Bambara", "name": "Bamanankan"},
    {"shotcut": "eu", "english_name": "Basque", "name": "euskera"},
    {"shotcut": "fj", "english_name": "Fijian", "name": ""},
    {"shotcut": "id", "english_name": "Indonesian", "name": "Bahasa indonesia"},
    {"shotcut": "mg", "english_name": "Malagasy", "name": ""},
    {"shotcut": "na", "english_name": "Nauru", "name": ""},
    {"shotcut": "xx", "english_name": "No Language", "name": "No Language"},
    {"shotcut": "qu", "english_name": "Quechua", "name": ""},
    {"shotcut": "sq", "english_name": "Albanian", "name": "shqip"},
    {"shotcut": "ti", "english_name": "Tigrinya", "name": ""},
    {"shotcut": "tw", "english_name": "Twi", "name": ""},
    {"shotcut": "wa", "english_name": "Walloon", "name": ""},
    {"shotcut": "ab", "english_name": "Abkhazian", "name": ""},
    {"shotcut": "bs", "english_name": "Bosnian", "name": "Bosanski"},
    {"shotcut": "af", "english_name": "Afrikaans", "name": "Afrikaans"},
    {"shotcut": "an", "english_name": "Aragonese", "name": ""},
    {"shotcut": "fy", "english_name": "Frisian", "name": ""},
    {"shotcut": "gu", "english_name": "Gujarati", "name": ""},
    {"shotcut": "ik", "english_name": "Inupiaq", "name": ""},
    {"shotcut": "ja", "english_name": "Japanese", "name": "日本語"},
    {"shotcut": "ko", "english_name": "Korean", "name": "한국어/조선말"},
    {"shotcut": "lg", "english_name": "Ganda", "name": ""},
    {"shotcut": "nl", "english_name": "Dutch", "name": "Nederlands"},
    {"shotcut": "os", "english_name": "Ossetian; Ossetic", "name": ""},
    {"shotcut": "el", "english_name": "Greek", "name": "ελληνικά"},
    {"shotcut": "bn", "english_name": "Bengali", "name": "বাংলা"},
    {"shotcut": "cr", "english_name": "Cree", "name": ""},
    {"shotcut": "km", "english_name": "Khmer", "name": ""},
    {"shotcut": "lo", "english_name": "Lao", "name": ""},
    {"shotcut": "nd", "english_name": "Ndebele", "name": ""},
    {"shotcut": "ne", "english_name": "Nepali", "name": ""},
    {"shotcut": "sc", "english_name": "Sardinian", "name": ""},
    {"shotcut": "sw", "english_name": "Swahili", "name": "Kiswahili"},
    {"shotcut": "tl", "english_name": "Tagalog", "name": ""},
    {"shotcut": "ur", "english_name": "Urdu", "name": "اردو"},
    {"shotcut": "ee", "english_name": "Ewe", "name": "Èʋegbe"},
    {"shotcut": "aa", "english_name": "Afar", "name": ""},
    {"shotcut": "co", "english_name": "Corsican", "name": ""},
    {"shotcut": "et", "english_name": "Estonian", "name": "Eesti"},
    {"shotcut": "is", "english_name": "Icelandic", "name": "Íslenska"},
    {"shotcut": "ks", "english_name": "Kashmiri", "name": ""},
    {"shotcut": "kr", "english_name": "Kanuri", "name": ""},
    {"shotcut": "ky", "english_name": "Kirghiz", "name": "??????"},
    {"shotcut": "kj", "english_name": "Kuanyama", "name": ""},
    {"shotcut": "nr", "english_name": "Ndebele", "name": ""},
    {"shotcut": "or", "english_name": "Oriya", "name": ""},
    {"shotcut": "wo", "english_name": "Wolof", "name": "Wolof"},
    {"shotcut": "za", "english_name": "Zhuang", "name": ""},
    {"shotcut": "ar", "english_name": "Arabic", "name": "العربية"},
    {"shotcut": "cv", "english_name": "Chuvash", "name": ""},
    {"shotcut": "fo", "english_name": "Faroese", "name": ""},
    {"shotcut": "hr", "english_name": "Croatian", "name": "Hrvatski"},
    {"shotcut": "ms", "english_name": "Malay", "name": "Bahasa melayu"},
    {"shotcut": "nb", "english_name": "Norwegian Bokmål", "name": "Bokmål"},
    {"shotcut": "rn", "english_name": "Rundi", "name": "Kirundi"},
    {"shotcut": "sn", "english_name": "Shona", "name": ""},
    {"shotcut": "st", "english_name": "Sotho", "name": ""},
    {"shotcut": "tr", "english_name": "Turkish", "name": "Türkçe"},
    {"shotcut": "am", "english_name": "Amharic", "name": ""},
    {"shotcut": "fa", "english_name": "Persian", "name": "فارسی"},
    {"shotcut": "hy", "english_name": "Armenian", "name": ""},
    {"shotcut": "pa", "english_name": "Punjabi", "name": "ਪੰਜਾਬੀ"},
    {"shotcut": "as", "english_name": "Assamese", "name": ""},
    {"shotcut": "ia", "english_name": "Interlingua", "name": ""},
    {"shotcut": "lv", "english_name": "Latvian", "name": "Latviešu"},
    {"shotcut": "lu", "english_name": "Luba-Katanga", "name": ""},
    {"shotcut": "mr", "english_name": "Marathi", "name": ""},
    {"shotcut": "mn", "english_name": "Mongolian", "name": ""},
    {"shotcut": "pt", "english_name": "Portuguese", "name": "Português"},
    {"shotcut": "th", "english_name": "Thai", "name": "ภาษาไทย"},
    {"shotcut": "tk", "english_name": "Turkmen", "name": ""},
    {"shotcut": "ve", "english_name": "Venda", "name": ""},
    {"shotcut": "dv", "english_name": "Divehi", "name": ""},
    {"shotcut": "gv", "english_name": "Manx", "name": ""},
    {"shotcut": "kl", "english_name": "Kalaallisut", "name": ""},
    {"shotcut": "kk", "english_name": "Kazakh", "name": "қазақ"},
    {"shotcut": "lt", "english_name": "Lithuanian", "name": "Lietuvių"},
    {"shotcut": "my", "english_name": "Burmese", "name": ""},
    {"shotcut": "sl", "english_name": "Slovenian", "name": "Slovenščina"},
    {"shotcut": "sd", "english_name": "Sindhi", "name": ""},
    {"shotcut": "cn", "english_name": "Cantonese", "name": "广州话 / 廣州話"},
    {"shotcut": "hi", "english_name": "Hindi", "name": "हिन्दी"},
    {"shotcut": "cy", "english_name": "Welsh", "name": "Cymraeg"},
    {"shotcut": "ht", "english_name": "Haitian; Haitian Creole", "name": ""},
    {"shotcut": "iu", "english_name": "Inuktitut", "name": ""},
    {"shotcut": "jv", "english_name": "Javanese", "name": ""},
    {"shotcut": "mh", "english_name": "Marshall", "name": ""},
    {"shotcut": "sa", "english_name": "Sanskrit", "name": ""},
    {"shotcut": "ss", "english_name": "Swati", "name": ""},
    {"shotcut": "te", "english_name": "Telugu", "name": "తెలుగు"},
    {"shotcut": "kg", "english_name": "Kongo", "name": ""},
    {"shotcut": "ml", "english_name": "Malayalam", "name": ""},
    {"shotcut": "uz", "english_name": "Uzbek", "name": "ozbek"},
    {"shotcut": "sg", "english_name": "Sango", "name": ""},
    {"shotcut": "xh", "english_name": "Xhosa", "name": ""},
    {"shotcut": "es", "english_name": "Spanish", "name": "Español"},
    {"shotcut": "su", "english_name": "Sundanese", "name": ""},
    {"shotcut": "ug", "english_name": "Uighur", "name": ""},
    {"shotcut": "yi", "english_name": "Yiddish", "name": ""},
    {"shotcut": "yo", "english_name": "Yoruba", "name": "Èdè Yorùbá"},
    {"shotcut": "zh", "english_name": "Mandarin", "name": "普通话"},
    {"shotcut": "he", "english_name": "Hebrew", "name": "עִבְרִית"},
    {"shotcut": "bo", "english_name": "Tibetan", "name": ""},
    {"shotcut": "ak", "english_name": "Akan", "name": ""},
    {"shotcut": "mo", "english_name": "Moldavian", "name": ""},
    {"shotcut": "ng", "english_name": "Ndonga", "name": ""},
    {"shotcut": "dz", "english_name": "Dzongkha", "name": ""},
    {"shotcut": "ff", "english_name": "Fulah", "name": "Fulfulde"},
    {"shotcut": "gd", "english_name": "Gaelic", "name": ""},
    {"shotcut": "ga", "english_name": "Irish", "name": "Gaeilge"},
    {"shotcut": "gl", "english_name": "Galician", "name": "Galego"},
    {"shotcut": "nv", "english_name": "Navajo", "name": ""},
    {"shotcut": "oc", "english_name": "Occitan", "name": ""},
    {"shotcut": "ro", "english_name": "Romanian", "name": "Română"},
    {"shotcut": "ta", "english_name": "Tamil", "name": "தமிழ்"},
    {"shotcut": "tn", "english_name": "Tswana", "name": ""},
    {"shotcut": "bg", "english_name": "Bulgarian", "name": "български език"}
  ];
  static const DATA_COUNTRIES = [
    {"shotcut": "AD", "english_name": "Andorra", "name": "Andorra"},
    {
      "shotcut": "AE",
      "english_name": "United Arab Emirates",
      "name": "United Arab Emirates"
    },
    {"shotcut": "AF", "english_name": "Afghanistan", "name": "Afghanistan"},
    {
      "shotcut": "AG",
      "english_name": "Antigua and Barbuda",
      "name": "Antigua & Barbuda"
    },
    {"shotcut": "AI", "english_name": "Anguilla", "name": "Anguilla"},
    {"shotcut": "AL", "english_name": "Albania", "name": "Albania"},
    {"shotcut": "AM", "english_name": "Armenia", "name": "Armenia"},
    {
      "shotcut": "AN",
      "english_name": "Netherlands Antilles",
      "name": "Netherlands Antilles"
    },
    {"shotcut": "AO", "english_name": "Angola", "name": "Angola"},
    {"shotcut": "AQ", "english_name": "Antarctica", "name": "Antarctica"},
    {"shotcut": "AR", "english_name": "Argentina", "name": "Argentina"},
    {
      "shotcut": "AS",
      "english_name": "American Samoa",
      "name": "American Samoa"
    },
    {"shotcut": "AT", "english_name": "Austria", "name": "Austria"},
    {"shotcut": "AU", "english_name": "Australia", "name": "Australia"},
    {"shotcut": "AW", "english_name": "Aruba", "name": "Aruba"},
    {"shotcut": "AZ", "english_name": "Azerbaijan", "name": "Azerbaijan"},
    {
      "shotcut": "BA",
      "english_name": "Bosnia and Herzegovina",
      "name": "Bosnia & Herzegovina"
    },
    {"shotcut": "BB", "english_name": "Barbados", "name": "Barbados"},
    {"shotcut": "BD", "english_name": "Bangladesh", "name": "Bangladesh"},
    {"shotcut": "BE", "english_name": "Belgium", "name": "Belgium"},
    {"shotcut": "BF", "english_name": "Burkina Faso", "name": "Burkina Faso"},
    {"shotcut": "BG", "english_name": "Bulgaria", "name": "Bulgaria"},
    {"shotcut": "BH", "english_name": "Bahrain", "name": "Bahrain"},
    {"shotcut": "BI", "english_name": "Burundi", "name": "Burundi"},
    {"shotcut": "BJ", "english_name": "Benin", "name": "Benin"},
    {"shotcut": "BM", "english_name": "Bermuda", "name": "Bermuda"},
    {"shotcut": "BN", "english_name": "Brunei Darussalam", "name": "Brunei"},
    {"shotcut": "BO", "english_name": "Bolivia", "name": "Bolivia"},
    {"shotcut": "BR", "english_name": "Brazil", "name": "Brazil"},
    {"shotcut": "BS", "english_name": "Bahamas", "name": "Bahamas"},
    {"shotcut": "BT", "english_name": "Bhutan", "name": "Bhutan"},
    {"shotcut": "BV", "english_name": "Bouvet Island", "name": "Bouvet Island"},
    {"shotcut": "BW", "english_name": "Botswana", "name": "Botswana"},
    {"shotcut": "BY", "english_name": "Belarus", "name": "Belarus"},
    {"shotcut": "BZ", "english_name": "Belize", "name": "Belize"},
    {"shotcut": "CA", "english_name": "Canada", "name": "Canada"},
    {
      "shotcut": "CC",
      "english_name": "Cocos  Islands",
      "name": "Cocos (Keeling) Islands"
    },
    {
      "shotcut": "CD",
      "english_name": "Congo",
      "name": "Democratic Republic of the Congo (Kinshasa)"
    },
    {
      "shotcut": "CF",
      "english_name": "Central African Republic",
      "name": "Central African Republic"
    },
    {
      "shotcut": "CG",
      "english_name": "Congo",
      "name": "Republic of the Congo (Brazzaville)"
    },
    {"shotcut": "CH", "english_name": "Switzerland", "name": "Switzerland"},
    {"shotcut": "CI", "english_name": "Cote D'Ivoire", "name": "Côte d’Ivoire"},
    {"shotcut": "CK", "english_name": "Cook Islands", "name": "Cook Islands"},
    {"shotcut": "CL", "english_name": "Chile", "name": "Chile"},
    {"shotcut": "CM", "english_name": "Cameroon", "name": "Cameroon"},
    {"shotcut": "CN", "english_name": "China", "name": "China"},
    {"shotcut": "CO", "english_name": "Colombia", "name": "Colombia"},
    {"shotcut": "CR", "english_name": "Costa Rica", "name": "Costa Rica"},
    {
      "shotcut": "CS",
      "english_name": "Serbia and Montenegro",
      "name": "Serbia and Montenegro"
    },
    {"shotcut": "CU", "english_name": "Cuba", "name": "Cuba"},
    {"shotcut": "CV", "english_name": "Cape Verde", "name": "Cape Verde"},
    {
      "shotcut": "CX",
      "english_name": "Christmas Island",
      "name": "Christmas Island"
    },
    {"shotcut": "CY", "english_name": "Cyprus", "name": "Cyprus"},
    {
      "shotcut": "CZ",
      "english_name": "Czech Republic",
      "name": "Czech Republic"
    },
    {"shotcut": "DE", "english_name": "Germany", "name": "Germany"},
    {"shotcut": "DJ", "english_name": "Djibouti", "name": "Djibouti"},
    {"shotcut": "DK", "english_name": "Denmark", "name": "Denmark"},
    {"shotcut": "DM", "english_name": "Dominica", "name": "Dominica"},
    {
      "shotcut": "DO",
      "english_name": "Dominican Republic",
      "name": "Dominican Republic"
    },
    {"shotcut": "DZ", "english_name": "Algeria", "name": "Algeria"},
    {"shotcut": "EC", "english_name": "Ecuador", "name": "Ecuador"},
    {"shotcut": "EE", "english_name": "Estonia", "name": "Estonia"},
    {"shotcut": "EG", "english_name": "Egypt", "name": "Egypt"},
    {
      "shotcut": "EH",
      "english_name": "Western Sahara",
      "name": "Western Sahara"
    },
    {"shotcut": "ER", "english_name": "Eritrea", "name": "Eritrea"},
    {"shotcut": "ES", "english_name": "Spain", "name": "Spain"},
    {"shotcut": "ET", "english_name": "Ethiopia", "name": "Ethiopia"},
    {"shotcut": "FI", "english_name": "Finland", "name": "Finland"},
    {"shotcut": "FJ", "english_name": "Fiji", "name": "Fiji"},
    {
      "shotcut": "FK",
      "english_name": "Falkland Islands",
      "name": "Falkland Islands"
    },
    {"shotcut": "FM", "english_name": "Micronesia", "name": "Micronesia"},
    {
      "shotcut": "FO",
      "english_name": "Faeroe Islands",
      "name": "Faroe Islands"
    },
    {"shotcut": "FR", "english_name": "France", "name": "France"},
    {"shotcut": "GA", "english_name": "Gabon", "name": "Gabon"},
    {
      "shotcut": "GB",
      "english_name": "United Kingdom",
      "name": "United Kingdom"
    },
    {"shotcut": "GD", "english_name": "Grenada", "name": "Grenada"},
    {"shotcut": "GE", "english_name": "Georgia", "name": "Georgia"},
    {"shotcut": "GF", "english_name": "French Guiana", "name": "French Guiana"},
    {"shotcut": "GH", "english_name": "Ghana", "name": "Ghana"},
    {"shotcut": "GI", "english_name": "Gibraltar", "name": "Gibraltar"},
    {"shotcut": "GL", "english_name": "Greenland", "name": "Greenland"},
    {"shotcut": "GM", "english_name": "Gambia", "name": "Gambia"},
    {"shotcut": "GN", "english_name": "Guinea", "name": "Guinea"},
    {"shotcut": "GP", "english_name": "Guadaloupe", "name": "Guadeloupe"},
    {
      "shotcut": "GQ",
      "english_name": "Equatorial Guinea",
      "name": "Equatorial Guinea"
    },
    {"shotcut": "GR", "english_name": "Greece", "name": "Greece"},
    {
      "shotcut": "GS",
      "english_name": "South Georgia and the South Sandwich Islands",
      "name": "South Georgia & South Sandwich Islands"
    },
    {"shotcut": "GT", "english_name": "Guatemala", "name": "Guatemala"},
    {"shotcut": "GU", "english_name": "Guam", "name": "Guam"},
    {"shotcut": "GW", "english_name": "Guinea-Bissau", "name": "Guinea-Bissau"},
    {"shotcut": "GY", "english_name": "Guyana", "name": "Guyana"},
    {
      "shotcut": "HK",
      "english_name": "Hong Kong",
      "name": "Hong Kong SAR China"
    },
    {
      "shotcut": "HM",
      "english_name": "Heard and McDonald Islands",
      "name": "Heard & McDonald Islands"
    },
    {"shotcut": "HN", "english_name": "Honduras", "name": "Honduras"},
    {"shotcut": "HR", "english_name": "Croatia", "name": "Croatia"},
    {"shotcut": "HT", "english_name": "Haiti", "name": "Haiti"},
    {"shotcut": "HU", "english_name": "Hungary", "name": "Hungary"},
    {"shotcut": "ID", "english_name": "Indonesia", "name": "Indonesia"},
    {"shotcut": "IE", "english_name": "Ireland", "name": "Ireland"},
    {"shotcut": "IL", "english_name": "Israel", "name": "Israel"},
    {"shotcut": "IN", "english_name": "India", "name": "India"},
    {
      "shotcut": "IO",
      "english_name": "British Indian Ocean Territory",
      "name": "British Indian Ocean Territory"
    },
    {"shotcut": "IQ", "english_name": "Iraq", "name": "Iraq"},
    {"shotcut": "IR", "english_name": "Iran", "name": "Iran"},
    {"shotcut": "IS", "english_name": "Iceland", "name": "Iceland"},
    {"shotcut": "IT", "english_name": "Italy", "name": "Italy"},
    {"shotcut": "JM", "english_name": "Jamaica", "name": "Jamaica"},
    {"shotcut": "JO", "english_name": "Jordan", "name": "Jordan"},
    {"shotcut": "JP", "english_name": "Japan", "name": "Japan"},
    {"shotcut": "KE", "english_name": "Kenya", "name": "Kenya"},
    {"shotcut": "KG", "english_name": "Kyrgyz Republic", "name": "Kyrgyzstan"},
    {"shotcut": "KH", "english_name": "Cambodia", "name": "Cambodia"},
    {"shotcut": "KI", "english_name": "Kiribati", "name": "Kiribati"},
    {"shotcut": "KM", "english_name": "Comoros", "name": "Comoros"},
    {
      "shotcut": "KN",
      "english_name": "St. Kitts and Nevis",
      "name": "St. Kitts & Nevis"
    },
    {"shotcut": "KP", "english_name": "North Korea", "name": "North Korea"},
    {"shotcut": "KR", "english_name": "South Korea", "name": "South Korea"},
    {"shotcut": "KW", "english_name": "Kuwait", "name": "Kuwait"},
    {
      "shotcut": "KY",
      "english_name": "Cayman Islands",
      "name": "Cayman Islands"
    },
    {"shotcut": "KZ", "english_name": "Kazakhstan", "name": "Kazakhstan"},
    {
      "shotcut": "LA",
      "english_name": "Lao People's Democratic Republic",
      "name": "Laos"
    },
    {"shotcut": "LB", "english_name": "Lebanon", "name": "Lebanon"},
    {"shotcut": "LC", "english_name": "St. Lucia", "name": "St. Lucia"},
    {"shotcut": "LI", "english_name": "Liechtenstein", "name": "Liechtenstein"},
    {"shotcut": "LK", "english_name": "Sri Lanka", "name": "Sri Lanka"},
    {"shotcut": "LR", "english_name": "Liberia", "name": "Liberia"},
    {"shotcut": "LS", "english_name": "Lesotho", "name": "Lesotho"},
    {"shotcut": "LT", "english_name": "Lithuania", "name": "Lithuania"},
    {"shotcut": "LU", "english_name": "Luxembourg", "name": "Luxembourg"},
    {"shotcut": "LV", "english_name": "Latvia", "name": "Latvia"},
    {
      "shotcut": "LY",
      "english_name": "Libyan Arab Jamahiriya",
      "name": "Libya"
    },
    {"shotcut": "MA", "english_name": "Morocco", "name": "Morocco"},
    {"shotcut": "MC", "english_name": "Monaco", "name": "Monaco"},
    {"shotcut": "MD", "english_name": "Moldova", "name": "Moldova"},
    {"shotcut": "ME", "english_name": "Montenegro", "name": "Montenegro"},
    {"shotcut": "MG", "english_name": "Madagascar", "name": "Madagascar"},
    {
      "shotcut": "MH",
      "english_name": "Marshall Islands",
      "name": "Marshall Islands"
    },
    {"shotcut": "MK", "english_name": "Macedonia", "name": "Macedonia"},
    {"shotcut": "ML", "english_name": "Mali", "name": "Mali"},
    {"shotcut": "MM", "english_name": "Myanmar", "name": "Myanmar (Burma)"},
    {"shotcut": "MN", "english_name": "Mongolia", "name": "Mongolia"},
    {"shotcut": "MO", "english_name": "Macao", "name": "Macau SAR China"},
    {
      "shotcut": "MP",
      "english_name": "Northern Mariana Islands",
      "name": "Northern Mariana Islands"
    },
    {"shotcut": "MQ", "english_name": "Martinique", "name": "Martinique"},
    {"shotcut": "MR", "english_name": "Mauritania", "name": "Mauritania"},
    {"shotcut": "MS", "english_name": "Montserrat", "name": "Montserrat"},
    {"shotcut": "MT", "english_name": "Malta", "name": "Malta"},
    {"shotcut": "MU", "english_name": "Mauritius", "name": "Mauritius"},
    {"shotcut": "MV", "english_name": "Maldives", "name": "Maldives"},
    {"shotcut": "MW", "english_name": "Malawi", "name": "Malawi"},
    {"shotcut": "MX", "english_name": "Mexico", "name": "Mexico"},
    {"shotcut": "MY", "english_name": "Malaysia", "name": "Malaysia"},
    {"shotcut": "MZ", "english_name": "Mozambique", "name": "Mozambique"},
    {"shotcut": "NA", "english_name": "Namibia", "name": "Namibia"},
    {"shotcut": "NC", "english_name": "New Caledonia", "name": "New Caledonia"},
    {"shotcut": "NE", "english_name": "Niger", "name": "Niger"},
    {
      "shotcut": "NF",
      "english_name": "Norfolk Island",
      "name": "Norfolk Island"
    },
    {"shotcut": "NG", "english_name": "Nigeria", "name": "Nigeria"},
    {"shotcut": "NI", "english_name": "Nicaragua", "name": "Nicaragua"},
    {"shotcut": "NL", "english_name": "Netherlands", "name": "Netherlands"},
    {"shotcut": "NO", "english_name": "Norway", "name": "Norway"},
    {"shotcut": "NP", "english_name": "Nepal", "name": "Nepal"},
    {"shotcut": "NR", "english_name": "Nauru", "name": "Nauru"},
    {"shotcut": "NU", "english_name": "Niue", "name": "Niue"},
    {"shotcut": "NZ", "english_name": "New Zealand", "name": "New Zealand"},
    {"shotcut": "OM", "english_name": "Oman", "name": "Oman"},
    {"shotcut": "PA", "english_name": "Panama", "name": "Panama"},
    {"shotcut": "PE", "english_name": "Peru", "name": "Peru"},
    {
      "shotcut": "PF",
      "english_name": "French Polynesia",
      "name": "French Polynesia"
    },
    {
      "shotcut": "PG",
      "english_name": "Papua New Guinea",
      "name": "Papua New Guinea"
    },
    {"shotcut": "PH", "english_name": "Philippines", "name": "Philippines"},
    {"shotcut": "PK", "english_name": "Pakistan", "name": "Pakistan"},
    {"shotcut": "PL", "english_name": "Poland", "name": "Poland"},
    {
      "shotcut": "PM",
      "english_name": "St. Pierre and Miquelon",
      "name": "St. Pierre & Miquelon"
    },
    {
      "shotcut": "PN",
      "english_name": "Pitcairn Island",
      "name": "Pitcairn Islands"
    },
    {"shotcut": "PR", "english_name": "Puerto Rico", "name": "Puerto Rico"},
    {
      "shotcut": "PS",
      "english_name": "Palestinian Territory",
      "name": "Palestinian Territories"
    },
    {"shotcut": "PT", "english_name": "Portugal", "name": "Portugal"},
    {"shotcut": "PW", "english_name": "Palau", "name": "Palau"},
    {"shotcut": "PY", "english_name": "Paraguay", "name": "Paraguay"},
    {"shotcut": "QA", "english_name": "Qatar", "name": "Qatar"},
    {"shotcut": "RE", "english_name": "Reunion", "name": "Réunion"},
    {"shotcut": "RO", "english_name": "Romania", "name": "Romania"},
    {"shotcut": "RS", "english_name": "Serbia", "name": "Serbia"},
    {"shotcut": "RU", "english_name": "Russia", "name": "Russia"},
    {"shotcut": "RW", "english_name": "Rwanda", "name": "Rwanda"},
    {"shotcut": "SA", "english_name": "Saudi Arabia", "name": "Saudi Arabia"},
    {
      "shotcut": "SB",
      "english_name": "Solomon Islands",
      "name": "Solomon Islands"
    },
    {"shotcut": "SC", "english_name": "Seychelles", "name": "Seychelles"},
    {"shotcut": "SD", "english_name": "Sudan", "name": "Sudan"},
    {"shotcut": "SE", "english_name": "Sweden", "name": "Sweden"},
    {"shotcut": "SG", "english_name": "Singapore", "name": "Singapore"},
    {"shotcut": "SH", "english_name": "St. Helena", "name": "St. Helena"},
    {"shotcut": "SI", "english_name": "Slovenia", "name": "Slovenia"},
    {
      "shotcut": "SJ",
      "english_name": "Svalbard & Jan Mayen Islands",
      "name": "Svalbard & Jan Mayen"
    },
    {"shotcut": "SK", "english_name": "Slovakia", "name": "Slovakia"},
    {"shotcut": "SL", "english_name": "Sierra Leone", "name": "Sierra Leone"},
    {"shotcut": "SM", "english_name": "San Marino", "name": "San Marino"},
    {"shotcut": "SN", "english_name": "Senegal", "name": "Senegal"},
    {"shotcut": "SO", "english_name": "Somalia", "name": "Somalia"},
    {"shotcut": "SR", "english_name": "Suriname", "name": "Suriname"},
    {"shotcut": "SS", "english_name": "South Sudan", "name": "South Sudan"},
    {
      "shotcut": "ST",
      "english_name": "Sao Tome and Principe",
      "name": "São Tomé & Príncipe"
    },
    {"shotcut": "SU", "english_name": "Soviet Union", "name": "Soviet Union"},
    {"shotcut": "SV", "english_name": "El Salvador", "name": "El Salvador"},
    {"shotcut": "SY", "english_name": "Syrian Arab Republic", "name": "Syria"},
    {
      "shotcut": "SZ",
      "english_name": "Swaziland",
      "name": "Eswatini (Swaziland)"
    },
    {
      "shotcut": "TC",
      "english_name": "Turks and Caicos Islands",
      "name": "Turks & Caicos Islands"
    },
    {"shotcut": "TD", "english_name": "Chad", "name": "Chad"},
    {
      "shotcut": "TF",
      "english_name": "French Southern Territories",
      "name": "French Southern Territories"
    },
    {"shotcut": "TG", "english_name": "Togo", "name": "Togo"},
    {"shotcut": "TH", "english_name": "Thailand", "name": "Thailand"},
    {"shotcut": "TJ", "english_name": "Tajikistan", "name": "Tajikistan"},
    {"shotcut": "TK", "english_name": "Tokelau", "name": "Tokelau"},
    {"shotcut": "TL", "english_name": "Timor-Leste", "name": "Timor-Leste"},
    {"shotcut": "TM", "english_name": "Turkmenistan", "name": "Turkmenistan"},
    {"shotcut": "TN", "english_name": "Tunisia", "name": "Tunisia"},
    {"shotcut": "TO", "english_name": "Tonga", "name": "Tonga"},
    {"shotcut": "TR", "english_name": "Turkey", "name": "Turkey"},
    {
      "shotcut": "TT",
      "english_name": "Trinidad and Tobago",
      "name": "Trinidad & Tobago"
    },
    {"shotcut": "TV", "english_name": "Tuvalu", "name": "Tuvalu"},
    {"shotcut": "TW", "english_name": "Taiwan", "name": "Taiwan"},
    {"shotcut": "TZ", "english_name": "Tanzania", "name": "Tanzania"},
    {"shotcut": "UA", "english_name": "Ukraine", "name": "Ukraine"},
    {"shotcut": "UG", "english_name": "Uganda", "name": "Uganda"},
    {
      "shotcut": "UM",
      "english_name": "United States Minor Outlying Islands",
      "name": "U.S. Outlying Islands"
    },
    {
      "shotcut": "US",
      "english_name": "United States of America",
      "name": "United States"
    },
    {"shotcut": "UY", "english_name": "Uruguay", "name": "Uruguay"},
    {"shotcut": "UZ", "english_name": "Uzbekistan", "name": "Uzbekistan"},
    {"shotcut": "VA", "english_name": "Holy See", "name": "Vatican City"},
    {
      "shotcut": "VC",
      "english_name": "St. Vincent and the Grenadines",
      "name": "St. Vincent & Grenadines"
    },
    {"shotcut": "VE", "english_name": "Venezuela", "name": "Venezuela"},
    {
      "shotcut": "VG",
      "english_name": "British Virgin Islands",
      "name": "British Virgin Islands"
    },
    {
      "shotcut": "VI",
      "english_name": "US Virgin Islands",
      "name": "U.S. Virgin Islands"
    },
    {"shotcut": "VN", "english_name": "Vietnam", "name": "Vietnam"},
    {"shotcut": "VU", "english_name": "Vanuatu", "name": "Vanuatu"},
    {
      "shotcut": "WF",
      "english_name": "Wallis and Futuna Islands",
      "name": "Wallis & Futuna"
    },
    {"shotcut": "WS", "english_name": "Samoa", "name": "Samoa"},
    {
      "shotcut": "XC",
      "english_name": "Czechoslovakia",
      "name": "Czechoslovakia"
    },
    {"shotcut": "XG", "english_name": "East Germany", "name": "East Germany"},
    {"shotcut": "XK", "english_name": "Kosovo", "name": "Kosovo"},
    {"shotcut": "YE", "english_name": "Yemen", "name": "Yemen"},
    {"shotcut": "YT", "english_name": "Mayotte", "name": "Mayotte"},
    {"shotcut": "YU", "english_name": "Yugoslavia", "name": "Yugoslavia"},
    {"shotcut": "ZA", "english_name": "South Africa", "name": "South Africa"},
    {"shotcut": "ZM", "english_name": "Zambia", "name": "Zambia"},
    {"shotcut": "ZW", "english_name": "Zimbabwe", "name": "Zimbabwe"}
  ];
}
